-- V1 — schéma initial, conforme au diagramme docs/diagrammes/D2-modele-donnees.md

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(150) NOT NULL,
    promotion_id BIGINT NOT NULL REFERENCES promotion (id)
);

CREATE TABLE session_cours (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(200) NOT NULL,
    promotion_id  BIGINT NOT NULL REFERENCES promotion (id),
    code          VARCHAR(6) NOT NULL,
    ouverture_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cloture_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_session_code UNIQUE (code)
);

-- RG2 : une seule présence par étudiant et par séance ; RG15 : source
CREATE TABLE presence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT NOT NULL REFERENCES session_cours (id),
    etudiant_id BIGINT NOT NULL REFERENCES etudiant (id),
    source      VARCHAR(10) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))
);

-- RG4 : compteur de codes inconnus consécutifs
CREATE TABLE tentative_code (
    etudiant_id   BIGINT PRIMARY KEY REFERENCES etudiant (id),
    echecs        INT NOT NULL DEFAULT 0,
    bloque_jusqua TIMESTAMP WITH TIME ZONE
);

-- RG12 : un seul exercice par étudiant et par séance ; statuts du diagramme D4
CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT NOT NULL REFERENCES session_cours (id),
    etudiant_id BIGINT NOT NULL REFERENCES etudiant (id),
    lien        VARCHAR(500) NOT NULL,
    statut      VARCHAR(25) NOT NULL,
    depose_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU'))
);

-- RG6 : un seul relecteur par exercice ; RG8 : note entière 0..20
CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT NOT NULL REFERENCES exercice (id),
    relecteur_id BIGINT NOT NULL REFERENCES etudiant (id),
    note         INT,
    commentaire  VARCHAR(2000),
    assignee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    rendue_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR note BETWEEN 0 AND 20)
);

CREATE INDEX idx_etudiant_promotion ON etudiant (promotion_id);
CREATE INDEX idx_session_promotion ON session_cours (promotion_id);
CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);
